### ISSUE TITLE
Explore g_flow_images issues

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/apex-frontend-boost#10]
@martindsouza said: 
> The Process that sets the static images location does not get run when a page validation fails and is re-displayed to the user.

Need to find a robust solution.

Application item G_APP_IMAGE maybe? Would be consistent with https://github.com/OraOpenSource/apex-gulp-stack/issues/5

**Comment by vincentmorneau** [comment]
For now I've used `G_APP_IMAGE` because `apex_application.g_flow_image` is reset upon each page load. Unless you come up with a better idea, I'd consider this issue closed.

**Comment by vincentmorneau** [comment]
Let me know if that issue is still on route for 2.0

**Comment by martindsouza** [comment]
@vincentmorneau If we want we can get rid of `G_APP_IMAGES` all together by using the proposed solution from #40 (i.e. use a cookie value).  This way we'd set `apex_application.g_flow_images` to the cookie value on each page load.

Pro: 
- We'd only need one Application Process which would have a BO of `DEV_ONLY`. There would be no need for a `{NOT DEV_ONLY}` BO
- No need for an additional application item
- Existing applications would not require any modifications as it could continue to use `APP_IMAGES`

Con: 
- The `APP_IMAGES` won't be set when a page validation fails.

Adding in `G_APP_IMAGES` is not a major issue except for existing applications with lots of files. Perhaps we could settle on offering both solutions and describing the differences between each one. In the end this really doesn't affect the gulp stack at all and more of an APEX configuration. 

If we want to offer both we should have one file in the documentation call `application-setup.md` (or similar) which outlines what needs to occur for each option. It may also make it easier for devs to follow one doc rather than having to do the two doc files we currently have.
