### ISSUE TITLE
Remove yargs for arguments

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-frontend-boost#37]
If we don't plan on having more options from the command line just us standard arguments instead of `-- --project=abc`.

See https://github.com/OraOpenSource/apex-diff/blob/master/app.js  (search for `arguments`)

**Comment by vincentmorneau** [comment]
@martindsouza I've investigated this.

Because of this part in `package.json`:
```json
"scripts": {
    "start": "gulp"
  }
```  
`npm start ...` substitutes `gulp`. This confuses the `process.argv` method used in apex-diff and it's unable to map simple parameters like `-project=abc`.

A solution would be to start the project using `gulp -project=abc`, but that requires gulp to be installed globally which would complicate the installation process.

The alternative that I chose was to use a 3rd party arguments handler like `yargs`.

What do you think?

**Comment by vincentmorneau** [comment]
Some documentation on the topic:
- http://stackoverflow.com/questions/11580961/sending-command-line-arguments-to-npm-script
- https://github.com/npm/npm/pull/5518
- https://docs.npmjs.com/cli/run-script
- http://stackoverflow.com/questions/33033864/unable-to-read-parameters-from-package-json

Basically, gulp takes any standard argument after the gulp keyword to define which task to run within the gulp file. 

So doing `npm start myProjectName` actually tells Gulp to run the myProjectName task inside the Gulpfile... 

Yargs makes it possible to define custom arguments without conflicting with Gulp, but requires the `-- --project=something` syntax.

I'll close this issue for now as I've been unable find a better solution. We may revisit later.
